/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3 */

#include "dev_manage_service.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(connect_parm_t, connect_parm_t, AUTO)


PB_BIND(device_info_t, device_info_t, AUTO)


PB_BIND(battery_info_t, battery_info_t, AUTO)


PB_BIND(system_time_t, system_time_t, AUTO)


PB_BIND(bind_status_t, bind_status_t, AUTO)


PB_BIND(unbind_status_t, unbind_status_t, AUTO)


PB_BIND(alg_ver_t, alg_ver_t, AUTO)


PB_BIND(app_auth_op_t, app_auth_op_t, AUTO)


PB_BIND(dev_auth_op_t, dev_auth_op_t, AUTO)


PB_BIND(status_info_t, status_info_t, AUTO)


PB_BIND(status_config_t, status_config_t, AUTO)


PB_BIND(status_config_t_sum_t, status_config_t_sum_t, AUTO)


PB_BIND(dev_status_info_t, dev_status_info_t, AUTO)



