/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3 */

#ifndef PB_SYS_BAT_PB_H_INCLUDED
#define PB_SYS_BAT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _bat_info_t {
    uint16_t voltage;
    uint8_t bat_level;
    int8_t bat_temp;
} bat_info_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define bat_info_t_init_default                  {0, 0, 0}
#define bat_info_t_init_zero                     {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define bat_info_t_voltage_tag                   1
#define bat_info_t_bat_level_tag                 2
#define bat_info_t_bat_temp_tag                  3

/* Struct field encoding specification for nanopb */
#define bat_info_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   voltage,           1) \
X(a, STATIC,   SINGULAR, UINT32,   bat_level,         2) \
X(a, STATIC,   SINGULAR, INT32,    bat_temp,          3)
#define bat_info_t_CALLBACK NULL
#define bat_info_t_DEFAULT NULL

extern const pb_msgdesc_t bat_info_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define bat_info_t_fields &bat_info_t_msg

/* Maximum encoded size of messages (where known) */
#define bat_info_t_size                          18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
