/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3 */

#ifndef PB_DEV_MANAGE_SERVICE_PB_H_INCLUDED
#define PB_DEV_MANAGE_SERVICE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _alg_ver_t {
    uint8_t step_alg_ver;
    uint8_t sleep_alg_ver;
    uint8_t wrist_raise_alg_ver;
    uint8_t swimming_alg_ver;
    uint8_t action_count_alg_ver;
    uint8_t activity_alg_ver;
    uint8_t allday_cal_alg_ver;
    uint8_t exercise_time_alg_ver;
    uint8_t trajectory_alg_ver;
    uint8_t sedentary_alg_ver;
    uint8_t boxing_action_alg_ver;
    uint8_t heart_rate_alg_ver;
    uint8_t blood_oxygen_alg_ver;
    uint8_t wear_alg_ver;
} alg_ver_t;

typedef struct _app_auth_op_t {
    uint8_t cmd;
} app_auth_op_t;

typedef struct _battery_info_t {
    uint16_t voltage;
    uint8_t level;
    int8_t temp;
    uint8_t chg_stat;
} battery_info_t;

typedef struct _bind_status_t {
    uint32_t status;
} bind_status_t;

typedef struct _connect_parm_t {
    uint16_t mtu;
    uint16_t mfs;
    uint8_t need_ack;
} connect_parm_t;

typedef struct _dev_auth_op_t {
    uint8_t cmd;
} dev_auth_op_t;

typedef struct _device_info_t {
    char manu_name[16];
    char mac[16];
    char sn[22];
    char hd_version[16];
    char fm_version[16];
    uint8_t has_bind;
    uint8_t dev_type;
} device_info_t;

typedef struct _status_config_t {
    uint8_t sensor_id;
    uint8_t status;
    uint16_t freq;
    uint8_t hr_type;
} status_config_t;

typedef struct _status_info_t {
    uint8_t workout_status;
    uint32_t operation_type;
} status_info_t;

typedef struct _system_time_t {
    uint32_t utc;
    int32_t time_zone;
    uint32_t display_type;
    uint32_t utc_ms;
} system_time_t;

typedef struct _unbind_status_t {
    uint32_t status;
} unbind_status_t;

typedef struct _status_config_t_sum_t {
    pb_size_t switch_config_count;
    status_config_t switch_config[10];
    uint8_t trans_flag;
} status_config_t_sum_t;

typedef struct _dev_status_info_t {
    uint8_t mode;
    bool has_status;
    status_info_t status;
    bool has_config;
    status_config_t_sum_t config;
} dev_status_info_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define connect_parm_t_init_default              {0, 0, 0}
#define device_info_t_init_default               {"", "", "", "", "", 0, 0}
#define battery_info_t_init_default              {0, 0, 0, 0}
#define system_time_t_init_default               {0, 0, 0, 0}
#define bind_status_t_init_default               {0}
#define unbind_status_t_init_default             {0}
#define alg_ver_t_init_default                   {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define app_auth_op_t_init_default               {0}
#define dev_auth_op_t_init_default               {0}
#define status_info_t_init_default               {0, 0}
#define status_config_t_init_default             {0, 0, 0, 0}
#define status_config_t_sum_t_init_default       {0, {status_config_t_init_default, status_config_t_init_default, status_config_t_init_default, status_config_t_init_default, status_config_t_init_default, status_config_t_init_default, status_config_t_init_default, status_config_t_init_default, status_config_t_init_default, status_config_t_init_default}, 0}
#define dev_status_info_t_init_default           {0, false, status_info_t_init_default, false, status_config_t_sum_t_init_default}
#define connect_parm_t_init_zero                 {0, 0, 0}
#define device_info_t_init_zero                  {"", "", "", "", "", 0, 0}
#define battery_info_t_init_zero                 {0, 0, 0, 0}
#define system_time_t_init_zero                  {0, 0, 0, 0}
#define bind_status_t_init_zero                  {0}
#define unbind_status_t_init_zero                {0}
#define alg_ver_t_init_zero                      {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define app_auth_op_t_init_zero                  {0}
#define dev_auth_op_t_init_zero                  {0}
#define status_info_t_init_zero                  {0, 0}
#define status_config_t_init_zero                {0, 0, 0, 0}
#define status_config_t_sum_t_init_zero          {0, {status_config_t_init_zero, status_config_t_init_zero, status_config_t_init_zero, status_config_t_init_zero, status_config_t_init_zero, status_config_t_init_zero, status_config_t_init_zero, status_config_t_init_zero, status_config_t_init_zero, status_config_t_init_zero}, 0}
#define dev_status_info_t_init_zero              {0, false, status_info_t_init_zero, false, status_config_t_sum_t_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define alg_ver_t_step_alg_ver_tag               1
#define alg_ver_t_sleep_alg_ver_tag              2
#define alg_ver_t_wrist_raise_alg_ver_tag        3
#define alg_ver_t_swimming_alg_ver_tag           4
#define alg_ver_t_action_count_alg_ver_tag       5
#define alg_ver_t_activity_alg_ver_tag           6
#define alg_ver_t_allday_cal_alg_ver_tag         7
#define alg_ver_t_exercise_time_alg_ver_tag      8
#define alg_ver_t_trajectory_alg_ver_tag         9
#define alg_ver_t_sedentary_alg_ver_tag          10
#define alg_ver_t_boxing_action_alg_ver_tag      11
#define alg_ver_t_heart_rate_alg_ver_tag         12
#define alg_ver_t_blood_oxygen_alg_ver_tag       13
#define alg_ver_t_wear_alg_ver_tag               14
#define app_auth_op_t_cmd_tag                    1
#define battery_info_t_voltage_tag               1
#define battery_info_t_level_tag                 2
#define battery_info_t_temp_tag                  3
#define battery_info_t_chg_stat_tag              4
#define bind_status_t_status_tag                 1
#define connect_parm_t_mtu_tag                   1
#define connect_parm_t_mfs_tag                   2
#define connect_parm_t_need_ack_tag              3
#define dev_auth_op_t_cmd_tag                    1
#define device_info_t_manu_name_tag              1
#define device_info_t_mac_tag                    2
#define device_info_t_sn_tag                     3
#define device_info_t_hd_version_tag             4
#define device_info_t_fm_version_tag             5
#define device_info_t_has_bind_tag               6
#define device_info_t_dev_type_tag               7
#define status_config_t_sensor_id_tag            1
#define status_config_t_status_tag               2
#define status_config_t_freq_tag                 3
#define status_config_t_hr_type_tag              4
#define status_info_t_workout_status_tag         1
#define status_info_t_operation_type_tag         2
#define system_time_t_utc_tag                    1
#define system_time_t_time_zone_tag              2
#define system_time_t_display_type_tag           3
#define system_time_t_utc_ms_tag                 4
#define unbind_status_t_status_tag               1
#define status_config_t_sum_t_switch_config_tag  1
#define status_config_t_sum_t_trans_flag_tag     2
#define dev_status_info_t_mode_tag               1
#define dev_status_info_t_status_tag             2
#define dev_status_info_t_config_tag             3

/* Struct field encoding specification for nanopb */
#define connect_parm_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   mtu,               1) \
X(a, STATIC,   SINGULAR, UINT32,   mfs,               2) \
X(a, STATIC,   SINGULAR, UINT32,   need_ack,          3)
#define connect_parm_t_CALLBACK NULL
#define connect_parm_t_DEFAULT NULL

#define device_info_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   manu_name,         1) \
X(a, STATIC,   SINGULAR, STRING,   mac,               2) \
X(a, STATIC,   SINGULAR, STRING,   sn,                3) \
X(a, STATIC,   SINGULAR, STRING,   hd_version,        4) \
X(a, STATIC,   SINGULAR, STRING,   fm_version,        5) \
X(a, STATIC,   SINGULAR, UINT32,   has_bind,          6) \
X(a, STATIC,   SINGULAR, UINT32,   dev_type,          7)
#define device_info_t_CALLBACK NULL
#define device_info_t_DEFAULT NULL

#define battery_info_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   voltage,           1) \
X(a, STATIC,   SINGULAR, UINT32,   level,             2) \
X(a, STATIC,   SINGULAR, INT32,    temp,              3) \
X(a, STATIC,   SINGULAR, UINT32,   chg_stat,          4)
#define battery_info_t_CALLBACK NULL
#define battery_info_t_DEFAULT NULL

#define system_time_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   utc,               1) \
X(a, STATIC,   SINGULAR, INT32,    time_zone,         2) \
X(a, STATIC,   SINGULAR, UINT32,   display_type,      3) \
X(a, STATIC,   SINGULAR, UINT32,   utc_ms,            4)
#define system_time_t_CALLBACK NULL
#define system_time_t_DEFAULT NULL

#define bind_status_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   status,            1)
#define bind_status_t_CALLBACK NULL
#define bind_status_t_DEFAULT NULL

#define unbind_status_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   status,            1)
#define unbind_status_t_CALLBACK NULL
#define unbind_status_t_DEFAULT NULL

#define alg_ver_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   step_alg_ver,      1) \
X(a, STATIC,   SINGULAR, UINT32,   sleep_alg_ver,     2) \
X(a, STATIC,   SINGULAR, UINT32,   wrist_raise_alg_ver,   3) \
X(a, STATIC,   SINGULAR, UINT32,   swimming_alg_ver,   4) \
X(a, STATIC,   SINGULAR, UINT32,   action_count_alg_ver,   5) \
X(a, STATIC,   SINGULAR, UINT32,   activity_alg_ver,   6) \
X(a, STATIC,   SINGULAR, UINT32,   allday_cal_alg_ver,   7) \
X(a, STATIC,   SINGULAR, UINT32,   exercise_time_alg_ver,   8) \
X(a, STATIC,   SINGULAR, UINT32,   trajectory_alg_ver,   9) \
X(a, STATIC,   SINGULAR, UINT32,   sedentary_alg_ver,  10) \
X(a, STATIC,   SINGULAR, UINT32,   boxing_action_alg_ver,  11) \
X(a, STATIC,   SINGULAR, UINT32,   heart_rate_alg_ver,  12) \
X(a, STATIC,   SINGULAR, UINT32,   blood_oxygen_alg_ver,  13) \
X(a, STATIC,   SINGULAR, UINT32,   wear_alg_ver,     14)
#define alg_ver_t_CALLBACK NULL
#define alg_ver_t_DEFAULT NULL

#define app_auth_op_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   cmd,               1)
#define app_auth_op_t_CALLBACK NULL
#define app_auth_op_t_DEFAULT NULL

#define dev_auth_op_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   cmd,               1)
#define dev_auth_op_t_CALLBACK NULL
#define dev_auth_op_t_DEFAULT NULL

#define status_info_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   workout_status,    1) \
X(a, STATIC,   SINGULAR, UINT32,   operation_type,    2)
#define status_info_t_CALLBACK NULL
#define status_info_t_DEFAULT NULL

#define status_config_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sensor_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   status,            2) \
X(a, STATIC,   SINGULAR, UINT32,   freq,              3) \
X(a, STATIC,   SINGULAR, UINT32,   hr_type,           4)
#define status_config_t_CALLBACK NULL
#define status_config_t_DEFAULT NULL

#define status_config_t_sum_t_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  switch_config,     1) \
X(a, STATIC,   SINGULAR, UINT32,   trans_flag,        2)
#define status_config_t_sum_t_CALLBACK NULL
#define status_config_t_sum_t_DEFAULT NULL
#define status_config_t_sum_t_switch_config_MSGTYPE status_config_t

#define dev_status_info_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   mode,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  status,            2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  config,            3)
#define dev_status_info_t_CALLBACK NULL
#define dev_status_info_t_DEFAULT NULL
#define dev_status_info_t_status_MSGTYPE status_info_t
#define dev_status_info_t_config_MSGTYPE status_config_t_sum_t

extern const pb_msgdesc_t connect_parm_t_msg;
extern const pb_msgdesc_t device_info_t_msg;
extern const pb_msgdesc_t battery_info_t_msg;
extern const pb_msgdesc_t system_time_t_msg;
extern const pb_msgdesc_t bind_status_t_msg;
extern const pb_msgdesc_t unbind_status_t_msg;
extern const pb_msgdesc_t alg_ver_t_msg;
extern const pb_msgdesc_t app_auth_op_t_msg;
extern const pb_msgdesc_t dev_auth_op_t_msg;
extern const pb_msgdesc_t status_info_t_msg;
extern const pb_msgdesc_t status_config_t_msg;
extern const pb_msgdesc_t status_config_t_sum_t_msg;
extern const pb_msgdesc_t dev_status_info_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define connect_parm_t_fields &connect_parm_t_msg
#define device_info_t_fields &device_info_t_msg
#define battery_info_t_fields &battery_info_t_msg
#define system_time_t_fields &system_time_t_msg
#define bind_status_t_fields &bind_status_t_msg
#define unbind_status_t_fields &unbind_status_t_msg
#define alg_ver_t_fields &alg_ver_t_msg
#define app_auth_op_t_fields &app_auth_op_t_msg
#define dev_auth_op_t_fields &dev_auth_op_t_msg
#define status_info_t_fields &status_info_t_msg
#define status_config_t_fields &status_config_t_msg
#define status_config_t_sum_t_fields &status_config_t_sum_t_msg
#define dev_status_info_t_fields &dev_status_info_t_msg

/* Maximum encoded size of messages (where known) */
#define connect_parm_t_size                      11
#define device_info_t_size                       97
#define battery_info_t_size                      21
#define system_time_t_size                       29
#define bind_status_t_size                       6
#define unbind_status_t_size                     6
#define alg_ver_t_size                           42
#define app_auth_op_t_size                       3
#define dev_auth_op_t_size                       3
#define status_info_t_size                       9
#define status_config_t_size                     13
#define status_config_t_sum_t_size               153
#define dev_status_info_t_size                   170

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
